name: CI - Build

on:
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        
        steps:
            - name: Mensaje Inicial
              run: echo "Iniciando el workflow de CI"

            - name: Checkout de código
              uses: actions/checkout@v2

            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: '10.0.x'

            - name: Verificar Versión .NET
              run: dotnet --version

            - name: Build del proyecto
              run: dotnet build src/Api/Api.csproj --configuration Release

            - name: Mensaje Final
              run: echo "Workflow de CI completado exitosamente"